---
development:
  DB_FILENAME: app/infrastructure/database/local/dev.db
  YOUTUBE_TOKEN: This_Is_A_Sample_Youtube_Token

test:
  DB_FILENAME: app/infrastructure/database/local/test.db
  YOUTUBE_TOKEN: This_Is_A_Sample_Youtube_Token

production:
  YOUTUBE_TOKEN: This_Is_A_Sample_Youtube_Token