---
# Name your file secrets.yml

development:
  # Infrastructure
  DB_FILENAME:    app/infrastructure/database/local/dev.db
  YOUTUBE_TOKEN:   create_youtube_token
  REPOSTORE_PATH: app/infrastructure/git/repostore
  # Application
  APP_HOST: http://localhost:9000
  SESSION_SECRET: <some secret>

app_test:
  # Infrastructure
  DB_FILENAME:    app/infrastructure/database/local/test.db
  REPOSTORE_PATH: app/infrastructure/git/repostore
  # Application
  APP_HOST: http://localhost:9000

test:
  # Infrastructure
  DB_FILENAME:    app/infrastructure/database/local/test.db
  YOUTUBE_TOKEN:   create_youtube_token
  REPOSTORE_PATH: app/infrastructure/git/repostore
  # Application
  APP_HOST: http://localhost:9000
  SESSION_SECRET: <some secret>

production:
  # Infrastructure
  # - assign DATABASE_URL in production
  YOUTUBE_TOKEN:   create_youtube_token
  REPOSTORE_PATH: app/infrastructure/git/repostore
  # Application
  APP_HOST: http://url.to.app
  SESSION_SECRET: <some secret>